### ISSUE TITLE
Error! Exception while fetching hosts : beat.hostname field not of type keyword or keyword mapping does not exist.

### ISSUE THREAD

**Issue by FlochonR** [sivasamyk/logtrail#250] opened 2018-03-05 13:20 UTC
Hello,

I take this error in Kibana : 
```
Error! Exception while fetching hosts : beat.hostname field not of type keyword or keyword mapping does not exist.
```

I have this configuration in logtrail.json: 
```
{
  "version" : 1,
  "index_patterns" : [
    {
      "es": {
        "default_index": "filebeat-*"
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "hostname" : "beat.hostname",
            "program": "source",
            "message": "message"
        },
        "message_format": "{{{source}}} {{{message}}}"
      },
      "color_mapping" : {
      }
    }
  ]
}
```

How to resolve this problem ?

**Comment by sivasamyk** [comment] 2018-03-12 13:58
Can you fetch mapping for beat.hostname from es and check if the field is of type keyword? What is the filebeat output used to inject logs to es?
`curl -XGET 'localhost:9200/filebeat-*/_mapping/doc/field/beat.hostname?pretty'`

**Comment by dbason** [comment] 2018-03-16 01:27
@sivasamyk I believe this is because you're using the CallWithInternal; if the internal user only has the kibana_system role then it won't have access to the logstash indices.  You're also doing the query against the admin cluster, when it should be the data cluster.

That said I've upgraded to 6.2.2 and giving the kibana user more permissions no longer works, so perhaps Elastic have changed how CallWithInternal works?  I've tried switching it to CallWithRequest, but I'm unsure how to access the current request headers with Kibana plugins.

**Comment by dbason** [comment] 2018-03-16 01:38
The reason I suspect it's a permission error is that I see the following lines in the log when it fails:
```
"message":"Cannot load keyword field for host. will use non-keyword field TypeError: Cannot read property 'keyword' of undefined"}
"message":"Cannot load keyword field for host.keyword. will use non-keyword field TypeError: Cannot read property 'keyword' of undefined"}
```
This looks like the query is failing to pull any results.

**Comment by sivasamyk** [comment] 2018-03-17 02:35
Duplicate of #248

**Comment by sivasamyk** [comment] 2018-07-07 11:44
Issue #248 is fixed in https://github.com/sivasamyk/logtrail/releases/tag/v0.1.28

**Closed by sivasamyk** 2018-07-07 11:44 UTC
