### ISSUE TITLE
Failed to parse unix format date field

### ISSUE THREAD

**Issue by jslusher** [sivasamyk/logtrail#6] opened 2016-09-19 22:15 UTC
I have some unix formatted date fields mapped to the @timestamp field and I think that is what is causing the following exception:

`Caused by: ElasticsearchParseException[failed to parse date field [1483249661000] with format [epoch_millis]]; nested: IllegalArgumentException[Invalid format: "1483249661000"];`

```
{
  "es": {
    "default_index": "logstash-*",
    "allow_url_parameter": false,
    "timezone": "America/Los_Angeles"
  },
  "tail_interval_in_seconds": 30,
  "max_buckets": 1000,
  "fields" : {
    "mapping" : {
        "timestamp" : "@timestamp",
        "display_timestamp" : "syslog_timestamp",
        "hostname" : "host",
        "program": "program",
        "message": "message"
    }
  }
}
```

**Comment by sivasamyk** [comment] 2016-09-20 01:46
@jslusher thanks for using logtrail. Can you paste your logstash conf file and sample document from ES ( use curl to query ES) ? What is the elasticsearch and logstash version you are using?

**Comment by kengibous** [comment] 2016-10-13 12:33
I believe I am having the same issue - getting error

Error! Exception while executing search query :[parse_exception] failed to parse date field [18611693012080] with format [epoch_millis]

This was working fine for a while, I did just recently upgrade elasticsearch to 2.4.1

Conf - 


{
  "es": {
    "default_index": "svcreqlogs-*",
    "allow_url_parameter": false,
	"timezone": "UTC"
  },  
  "tail_interval_in_seconds": 10,
  "max_buckets": 500,
  "fields" : {
    "mapping" : {
        "timestamp" : "@timestamp",
        "display_timestamp" : "@timestamp",
        "hostname" : "s-computername",
        "program": "appName",
        "message": "action"
    }
  }
}

**Comment by sivasamyk** [comment] 2016-10-13 12:56
@kengibous looks like some mapping is not present.  Are Kibana views working fine? If you are using logstash, can you paste you logstash config?

**Comment by kengibous** [comment] 2016-10-13 13:10
Kibana views appear fine.  Yes I am using logstash.  This has been working fine for weeks until recently.

Conf for logstash (logstash 2.4.0) - I did blank out some sensitive fields.  Thank you!


[logstash.conf.txt](https://github.com/sivasamyk/logtrail/files/527161/logstash.conf.txt)

**Comment by kengibous** [comment] 2016-10-13 14:10
@sivasamyk sorry to waste your time, i think the issue is with the data that was logged - it was logged with timestamp Sat Oct 13 2559 02:43:32, and it appears logtrail uses that timestamp which in epoch time is 18611693012080.  Is there away that logtrail could use the system time instead of a time from the logged message data?  Hope that makes sense...

**Comment by sivasamyk** [comment] 2016-10-13 14:20
If I am correct, you mean there are messages with timestamp as Sat Oct 13 2559 02:43:32 in Elasticsearch. When you open logtrail first time, it get the latest 500 events from ES. The live tail will use the timestamp of latest event to fetch events. I assume you are seeing logs when you open logtrail for first time. The live tail queries are failing.

**Comment by sivasamyk** [comment] 2016-10-14 16:26
@kengibous Did your issue got resolved? Let me know if I can help.

**Comment by sivasamyk** [comment] 2017-10-29 13:07
Closing this issue. Reopen if still reproducible.

**Closed by sivasamyk** 2017-10-29 13:07 UTC
