### ISSUE TITLE
Wrong order of timestamp on the main console

### ISSUE THREAD

**Issue by smartinov** [sivasamyk/logtrail#109] opened 2017-05-26 13:54 UTC
The console displays the messages in a wrong chronological order

https://image.prntscr.com/image/1a01a46049304d26b7f92a230a26c46d.png

When i order by timestamp (kibana) i get the correct results.

Is there any obvious reason why this should be like that? 

Config:
```json
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "logstash-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 2,
      "max_buckets": 500,
      "nested_objects" : false,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "@timestamp",
            "host":"service_name"
            "message": "message"
        }
      }
    }
  ]
}
```

**Comment by sivasamyk** [comment] 2017-05-26 14:51
@smartinov Is it happening while doing live tail or even during not query ( on clicking search or opening the app for first time)? There was an issue of ordering in live tail when the event rate is high which has been fixed in later releases.

Can you let me know the logtrail version you are using?

**Comment by smartinov** [comment] 2017-05-26 15:23
Hm, the weird part is that it started to work correctly (or is working correctly atm).  Maybe the first batch was weird since it did a burst of events.

Seems to be working now however i did reduce the max_buckets to 100 and max_events to 1000, but i don't think it has something to do with this.

Can try to up the numbers again.

I'm using the latest (0.1.13)

**Comment by sivasamyk** [comment] 2017-05-26 15:31
If the issue is happening during tail, you can set
es_index_time_offset_in_seconds in logtrail.json to 10 seconds.

**Comment by Bizzelicious** [comment] 2017-06-02 08:52
What's your refresh time? (tail_interval_in_seconds) If you have a fast refresh time (1-3s) then you might end up with logs in the wrong order.
We had a pretty long discussion about this in this thread: https://github.com/sivasamyk/logtrail/issues/32#issuecomment-273177972

**Comment by smartinov** [comment] 2017-06-02 09:56
Got it! Guess it was the tail_interval_in_seconds !
Thanks for the support!

Closing this issue.

**Comment by sheinbergon** [comment] 2017-09-05 18:20
@sivasamyk   this is still the case when  a field other then ```@timestamp``` is used for "timestamp" or "display_timestamp". We should repopen this issue.

**Comment by sivasamyk** [comment] 2017-09-05 18:27
@sheinbergon Logtrail sorts the events based on `@timestamp` field. User can configure a different field other than `@timestamp` to display_timestamp ( which will be displayed in console). So if the `@timestamp` and display_timestamp field are not in sync, the event order can be different. Can you share you logtrail.json?

**Comment by sheinbergon** [comment] 2017-09-05 18:38
Sure thing :

```json
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "application-logs-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 10,
      "display_timezone": "Etc/UTC",
      "display_timestamp_format": "YYYY-MM-DDTHH:mm:ss.SSS",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 20000,
      "fields" : {
        "mapping" : {
            "timestamp" : "time",
            "display_timestamp" : "time",
            "hostname" : "beat.hostname",
            "program": "app_name",
            "message": "msg"
        },
        "message_format": "[ {{{level}}} | {{{logger}}} | {{{thread}}} | {{{app_version}}} | {{{marker}}} ] - {{{msg}}}"
      }
    }
  ]
}
```

Where ```time``` is a field of type ```date```, input as ISO8601 timestamp.

**Comment by derandreasberger** [comment] 2017-09-15 11:29
Hello, 

same issue, I've played around with the settings, but it seems to me this is not related to (or not only related to) which timestamp is used.
For user-acceptance we need a low tail_interval_in_seconds (I can see keeping order of events in live-tail might be tricky, no need to argue that), but: When pausing the events should really be in order, regardless of which configuration-values have been set!

logtrail.json:
`
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "xxx_*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 2,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "YYYY-MM-DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 10000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "display_timestamp" : "log_date",
            "hostname" : "host",
            "program": "appname",
            "message": "message"
        },
        "message_format": "{{{env}}} - {{{message}}}"
      }
    }
  ]
}
`
Output (state: PAUSE + 2 search-values):
`
2017-09-15 10:54:10 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:10,872 [Thread-1994] INFO  ...
2017-09-15 10:54:11 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:11,013 [Thread-1994] INFO  ...
2017-09-15 10:54:10 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:10,924 [Thread-1994] INFO  ...
2017-09-15 10:54:11 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:11,013 [Thread-1994] INFO  ...
2017-09-15 10:54:11 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:11,010 [Thread-1994] INFO  ...
2017-09-15 10:54:10 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:10,924 [Thread-1994] INFO  ...
2017-09-15 10:54:10 ip-10-16-27-184 xxx:  [STAGE] 2017-09-15 10:54:10,872 [Thread-1994] INFO  ...
`

We would really appreciate to use logtrail, please let me know if this issue can be resolved!
Thanks,
Andreas

**Comment by Bizzelicious** [comment] 2017-09-15 12:00
@derandreasberger We have the same issue, do you use a cluster setup with logstash and elasticsearch? Like this:
![example-elk - page 1](https://user-images.githubusercontent.com/13730491/30481142-6484e234-9a1d-11e7-99c0-f5388a51de4e.jpeg) 


We did a **workaround** so the logagent is instead of loadbalancing the traffic between the logstashes just sends data to one of them randomly (decided at startup) and failovers to the other if needed. That allowed us to have a low refresh time (3s) in Logtrail. Then atleast logs from the same agent will be in the same order.

But I would love to have some logical check in Logtrail to actually check the timestamps, but I think that will be very hard since the data PUT in elasticsearch does not have to be in order. It's Kibana which sorts the logs. Have a look at this thread where we discussed it before: #32

**Comment by sivasamyk** [comment] 2017-09-15 12:32
@derandreasberger I see that the `timestamp` and `display_timestamp`  maps to different fields. By default `@timestamp` field is added by logstash based on event processing time ( unless we use date filter to map `log_date` to `@timestamp`). Can you map both `timestamp` and `display_timestamp` to `@timestamp` field and confirm if the issue is still seen? Also do you configure logstash to use multiple filter worker threads?

**Comment by sheinbergon** [comment] 2017-09-15 12:37
Hi @sivasamyk . As written above, this is only seen when using fields other then `@timestamp` for `timestamp` and `display_timestamp`

**Comment by derandreasberger** [comment] 2017-09-15 12:39
@Bizzelicious : Thanks for the hint, I've been reading #32 now. I'm going to check the es_index_time_offset_in_seconds-parameter to see if it's feasible to modify it.

@sivasamyk : Ok, I'm going to change both fileds to @timestamp. I'm going to check on the filter-workers, not sure about these settings. 

ps: We're using only one logstash-server and one single ES cluster for now (new version still in testing).

**Comment by sivasamyk** [comment] 2017-09-15 12:50
@sheinbergon I see you use beat to ship logs. If you are using logstash to parse the logs, can let me know how the `time` field is derived? Also confirm if your logstash has multiple filter worker threads.

**Comment by sheinbergon** [comment] 2017-09-15 12:55
@sivasamyk  the time field is dervied from the log4j2 iso8601 timestamp ( i'm shipping java application logs ).
I do not have multiple filter work threads. In general I can confirm the data in the elastic cluster makes sense as far as the  timestamps are recorded. Are you suggesting there's an issue with timestamps themselves ?

**Comment by sivasamyk** [comment] 2017-09-15 13:10
@sheinbergon Just wanted to understand how `time` field is derived. Is the order wrong only during live tail and even during normal retrieval (like when you search for items)?

**Comment by sheinbergon** [comment] 2017-09-15 13:17
It's wrong in both

**Comment by sivasamyk** [comment] 2017-09-15 13:26
During search, logtrail sets the order by column (in search query) to the field mapped to `timestamp`. The sorting is done by elasticsearch and logtrail displays the events in same order returned by ES. Can you confirm if Kibana discover UI display events in proper order?

**Comment by sheinbergon** [comment] 2017-09-15 13:38
what's the search term I should enter in the discover UI ?

**Comment by sivasamyk** [comment] 2017-09-15 13:46
Just make sure the events that are shown in wrong order in logtrail, are visible in Kibana UI and check the timestamp and order for these events (Kibana sorts events by timestamp field. You can configure `time` field as timestamp in Kibana under Management/Index Patterns)

**Comment by derandreasberger** [comment] 2017-09-15 13:47
On my side i can confirm Kibana displayed the events in wrong order at first, only since I added our original "log_date" and used it to sort, the order got corrected. So i guess this is an ES issue then?
(btw: We're using Amazon ES SaaS 5.2)

**Comment by sheinbergon** [comment] 2017-09-15 13:52
TIme filter filed name is already set to ```time``` ( my custome field). Events in the discover UI seem OK...

**Comment by sheinbergon** [comment] 2017-09-15 13:56
Time filter field is already set to my custom field. AS far as the discover UI. without any lucene filters applied I get somewhat random ordering. Isn't that the expected behavior. When I add a time range filter ( by the time field ) the ordering is correct

**Comment by sivasamyk** [comment] 2017-09-15 14:09
By adding time range filter means, you added in the Seach box or changed in Time Selector in top right corner? It is strange that even during search the order is wrong, because logtrail displays the events the same order returned by ES.

**Comment by derandreasberger** [comment] 2017-09-18 09:16
Sorting works for us properly now!
I'm sorry, but I really don't know what I have changed since the very beginning - basically i just aligned all sorting options and date-formats and now it works.
Just make sure to use the same date-field in all settings, I think display_timestamp is used for the sorting in logtrail rather than 'timestamp' which is probably used for filters only... E.g.
`            "timestamp" : "log_date",
             "display_timestamp" : "log_date",`

**Comment by sheinbergon** [comment] 2017-09-18 09:59
@derandreasberger  @sivasamyk.

- I'm using my ```time``` field for both ```display_timestamp``` and ```timestamp```.
- My ```time``` field is already defined as the ```Time Filter field name``` in Kibana.
- My ```time``` fields is defined as ```date``` in the index template (logstash/Elasticsearch)

Yet : 
- Logtrail messes up the time order when searching a timerange. Live-tail seems to be alright.
- Logtrail sometimes messes up the time offset calculation, displaying time-jumps of 3 hours ( we're at UTC+03:00 currently ) where  no jump has actually taken place.
- When using ```@timestamp``` as the logtrail's ```timestamp/display_timestamp``` source, ordering works ok, but then we miss out on the actual timestamps where things happend.

Any suggestions/ideas welcomed.

@sivasamyk  Your work is amazing, and we really appreciate your efforts in making this plugin come to life. But at current state of things, It's not really useful.

My current configration is :
```json
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "application-logs-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 10,
      "display_timezone": "Etc/UTC",
      "display_timestamp_format": "YYYY-MM-DDTHH:mm:ss.SSS",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 20000,
      "fields" : {
        "mapping" : {
            "timestamp" : "time",
            "display_timestamp" : "time",
            "hostname" : "beat.hostname",
            "program": "app_name",
            "message": "msg"
        },
        "message_format": "[ {{{level}}} | {{{logger}}} | {{{thread}}} | {{{app_version}}} | {{{marker}}} ] - {{{msg}}}"
      }
    }
  ]
}
```

**Comment by sivasamyk** [comment] 2017-09-18 10:18
@sheinbergon Can you share screenshot of the logtrail where the time ordering is not correct? I assume the `time` field is stored in UTC in elasticsearch.

**Comment by sivasamyk** [comment] 2017-09-18 10:39
@derandreasberger `timestamp` mapped field is used for sorting and range calculation etc. `display_timestamp` is used only to show in the events view and is formatted based on specified format and timezone in logtrail,json. `disaply_timestamp` was initially introduced an option to show source log time in events view (when source time is coarse or in multiple tz) . with introduction of `message_format` source time can be added as field in message_format and both timestamp and display_timestamp can be mapped to same field.

**Comment by sivasamyk** [comment] 2017-09-18 13:28
@sheinbergon I tried indexing https://issues.cloudera.org/secure/attachment/10907/zookeeper-cmf-zookeeper1-SERVER-hadoop-108.log file into ES and displaying in logtrail. This file contains ~4000 log enties. Assuming the timestamp in the file is UTC and configuring logtrail to display time in UTC ( using `logdate` as timestamp ), I was able to see all the logs sorted properly. Find attached my logstash and logtrail configuration. I configured logstash to interpret logdate in UTC TZ.

In the attached screenshot, I have displayed both logtrail timestamp and actual log timestamp and they are matching and the sort order is proper. Let me know you logstash configuration.

![logtrail-zookeeper](https://user-images.githubusercontent.com/1464186/30544179-41c32cb4-9ca3-11e7-8581-38154ebe2eee.png)

**logtrail.json**

```json
{
  "index_patterns" : [
    {      
      "es": {
        "default_index": "logstash-zookeeper",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "Etc/UTC",
      "display_timestamp_format": "YYYY MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "logdate",
            "display_timestamp" : "logdate",
            "hostname" : "host",
            "program": "log_level",
            "message": "log_message"
        },
        "message_format": "{{{message}}}"
      },
      "color_mapping" : {
        
      }
    }  
  ]
}
```
**logstash.conf**

```ruby
input {
        file {
                path => "/home/user/lab/zookeeper-release-3.4.3/logs/zookeeper.log"
                start_position => beginning
                sincedb_path => "/tmp/sincedb"
        }
}

filter {
        grok {
                match => {
                        "message" => "%{TIMESTAMP_ISO8601:logdate} %{LOGLEVEL:log_level} %{JAVACLASS:package}: %{GREEDYDATA:log_message}"
                }
        }
        date {
                match => ["logdate", "yyyy-MM-dd HH:mm:ss,SSS", "ISO8601"]
                target => "logdate"
                timezone => "Etc/UTC"
        }
}

output {
        elasticsearch {
		      index => "logstash-zookeeper"
        }
}
```

**Comment by sheinbergon** [comment] 2017-09-18 21:31
OK. 

So giving the logtrail issue a second look. I can confirm the issue not ordering, but actually events jumping timezone offsets of -3 hours ( we are GMT+3 ). This bug is repetitive, meaning we're seeing several -3 jumps 

All of our servers are in sync and log the events in UTC ( we don't have server running using IDT).
It looks like the logtrail gets confused somehow and orders events incorrectly. 

I'm viewing from a laptop in UTC + 3
Logs are logged at UTC
Logtrail shows events in UTC - 3

**Looking at your above logstash configuration. I don't have the date block in the logstash configuration but I am using  ISO8601 formats in Log4j2. Is that crucial for proepr ordering to work ?**

![nonsense-ordering](https://user-images.githubusercontent.com/4031179/30565096-c229dec6-9ccf-11e7-8463-26b20720f27b.png)
![timezone-jump-2](https://user-images.githubusercontent.com/4031179/30565098-c2305238-9ccf-11e7-89d2-4c427cc8ffff.png)
![timezone jump](https://user-images.githubusercontent.com/4031179/30565097-c22cfc5a-9ccf-11e7-8bf3-058dc4e5d2be.png)

**Comment by sivasamyk** [comment] 2017-09-19 01:43
@sheinbergon Logtrail does not order the events. The ordering is done by elasticsearch based on field mapped to `timestamp`. Logtrail just displays the events. I see that you have configured the `display_timezone` to UTC.  Logtrail will convert all the `display_timestamp` (which is mapped to `time`) to UTC in the view. I would recommend you to add a date filter and map all date to `time` target field and timezone as `Etc/UTC`

**Comment by derandreasberger** [comment] 2017-09-19 16:33
@sivasamyk I've checked out the source, and fixed the UTC issue which sheinbergon and myself are facing. I've done the changes on a 5.2 tag (due to some SaaS elasticsearch/kibana version conflicts), I'm looking forward to get a working branch for 5.5 (probably tomorrow). Once I'm done with that, I'm going to post you, to see how and if you want to get a pull-request/a new branch pushed.

**Comment by sivasamyk** [comment] 2017-09-19 16:39
Sure. Let me know once you push your changes to a new branch.

**Comment by sivasamyk** [comment] 2017-09-19 16:47
@derandreasberger Mapping proper date field using date filter in logstash config and setting timestamp and display_timestamp should solve this issue. Curious to know your code changes :)

**Comment by derandreasberger** [comment] 2017-09-20 07:16
@sivasamyk I've checked out the source yesterday, and fixed the UTC issue which sheinbergon and myself are facing. I've done the changes on a 5.2 tag, I'm looking forward to get a working branch for 5.5 today. Once I'm done with that, I'm going to post you, then we can figure out how to deal with the fix (pull-request maybe?).

**Comment by derandreasberger** [comment] 2017-09-20 10:28
@sivasamyk Ok, 5.5.3 branch is ready. Can you grant permissions for me to push to your git? I could also provide a patch-file via mail or the like if you want!
`C:\kibana\kibana\plugins\logtrail (5.5.3_utc) (logtrail@0.1.20)`
`git push -u origin 5.5.3_utc`
`remote: Permission to sivasamyk/logtrail.git denied to derandreasberger.`
`fatal: unable to access 'https://github.com/sivasamyk/logtrail.git/': The requested URL returned error: 403`

**Comment by sivasamyk** [comment] 2017-09-20 10:31
Fork my repo and please send a pull request. If not possible a patch is fine.

**Comment by sheinbergon** [comment] 2017-09-21 13:57
@derandreasberger @sivasamyk any progress/news about the fix ?

**Comment by sivasamyk** [comment] 2017-09-21 14:02
@sheinbergon I am yet to review the fix. I see that we are sorting the events locally in browser, which I foresee some issues. As mentioned earlier, I am also planning to remove `display_timestamp` in future release.  Did you get a chance to add date filter in logstash and see if the events are displayed properly?

**Comment by sheinbergon** [comment] 2017-09-21 14:06
@sivasamyk  I've just added  the filter fix. It'll take some time for the ES to  amass events.
Is the fix supposed to solve the scenario portrayed in the screenshots I provided ?

**Comment by sivasamyk** [comment] 2017-09-21 14:20
@sheinbergon  Thanks. The date filter will ensure all events are converted to same timezone and timestamp format.  Can you configure your `message_format` to include `time` field also and get screenshot? This will help to compare the actual timestamp received from source and display_timestamp.  From the screenshot I see that events from same source are suddenly displayed in different time zone. I assume these new events are not added via live tail.

**Comment by sheinbergon** [comment] 2017-09-21 14:31
@sivasamyk. No. that's not the case. What happens is that actual events from _x-3_ hours are suddenly displayed after events from time _x_ . This is probably related to the browser sorting and -3 timezone display issue I mentioned earlier - Logtrail deduces -3 timezone incorrectly, gets 'confused' and starts logging an event from 3 hours ago ( which  are also logged in -3 offset ). This issue repeats itself when scrolling.

**Comment by sivasamyk** [comment] 2017-09-21 15:35
@sheinbergon I think these sudden new events are fetched during the first tail query from logtrail, when logtrail queries for all events whose time stamp is larger than latest event's. Logtrail/browser does not sort the events. I think there is some timezone mismatch. Let me know the behavior after adding date filter and mapping the `time` field. Make sure you specify the timezone of incoming event's timestamp if not available in timestamp. In you case it should be like

```
date {
      match => [ "time", "ISO8601" ]
      target => "time"
      timezone => "Etc/UTC" # assuming the incoming timestamps are UTC
    }
```

**Comment by sheinbergon** [comment] 2017-09-21 15:48
@sivasamyk , Yep that's what I did.

Let's talk in a few days.

**Comment by sheinbergon** [comment] 2017-09-27 16:55
@sivasamyk  I can confirm the above fix solved the issues/problem.
You should consider hardcoding inside your setup wiki.

Appreciate all of your hard work & effort put into resolving this issue.

**Comment by sivasamyk** [comment] 2017-09-28 04:46
@sheinbergon I have added a new repo for collecting example logtrail configuration for various systems @ https://github.com/sivasamyk/logtrail-config-examples . You can look into the specific dir for example configs and respective screenshots. 
@derandreasberger Checkout the repo @ https://github.com/sivasamyk/logtrail-config-examples for sample configs
I have updated logtrail README to point to these examples.

**Closed by sivasamyk** 2017-09-28 04:46 UTC

**Comment by derandreasberger** [comment] 2017-09-28 06:50
@sivasamyk the timezone-configuration settings are looking promising, I'm going to check it out soon. Thanks for all the effort!

**Comment by mindcurv-jerald** [comment] 2018-03-07 08:17
Hi @sivasamyk 

I know this issue is closed but I face the same issue described in the title. i.e the wrong order of the timestamp :(


As you can see in the below logs  the "13:59:53" comes after "14:00:01"

`Mar 06 14:00:01 vmDHB04091 Datahub:  2018-03-06T14:00:01.270+0100 [INFO] [c.h.d.l.i.RawItemLoggingService] SAPPRODUCT_INBOUND_POOL RawCHRMAS uuid=55f5fdd4-f6ac-44be-9c34-0da24839bf5b id=22942 delete=false action=31 fields={E1CABNM-ATSCH_LONG=null, E1CABNM-E1TEXTL-TDFORMAT=null, 
Mar 06 13:59:53 vmDHB04091 Datahub:  2018-03-06T13:59:53.418+0100 [DEBUG] [c.h.d.s.IDOCMappingService] The parsing of the IDOC took 47 milliseconds. 1 IDOCs, 6135 fragments, 92048 values.
Mar 06 13:59:53 vmDHB0810201 Datahub:  2018-03-06T13:59:53.433+0100 [INFO] [c.h.d.r.r.StatusCountResource] Received GET request /status-counts/raw/ with args [null] with user [admin]
`
Following is my logtrail.json
`{
  "index_patterns" : [
    {
      "es": {
        "default_index": "filebeat*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 10,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@timestamp",
            "hostname" : "beat.hostname",
            "program": "application",
            "message": "message"
        },
        "message_format": "{{{message}}}"
      }
    }
  ]
}
`

- I use Kibana and Elasticsearch version **6.0.1** and logtrail version is **6.0.1-0.1.23**
- I don't use logstash  but use ingest pipeline for parsing the logs, timestamp etc.
- I think, there are more than 1000 log events in 1 second.

Could you please suggest, how to fix this?

**Comment by mindcurv-jerald** [comment] 2018-03-12 12:31
@sivasamyk Any luck on the above issue ?
Should I create a separate ticket for this ?
