### ISSUE TITLE
Log not shown when using dot notations

### ISSUE THREAD

**Issue by sasso** [sivasamyk/logtrail#120] opened 2017-06-10 19:29 UTC
```
{
  "index_patterns" : [
    {      
      "es": {
        "default_index": "kubernetes-*",
        "allow_url_parameter": false       
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : true,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
          "timestamp" : "@timestamp",
          "display_timestamp" : "@timestamp",
          "hostname" : "kubernetes.namespace_name",
          "program": "kubernetes.container_name",
          "message": "docker.log"
        },
        "message_format": "({{{kubernetes.pod_name}}}) {{{docker.log}}}"
      }
    }  
  ]
}

```

nested_objects is working for `hostname` and `program` but it does not render message_format.

I am using `0.1.11/logtrail-5.3.2-0.1.11`

**Comment by sivasamyk** [comment] 2017-06-11 15:37
@sasso looks like bug. A temporary workaround is to change your message format to ({{{[kubernetes.pod_name]}}}) {{{[docker.log]}}}. But this will make both the fields as hyperlinks.

**Comment by sasso** [comment] 2017-06-11 15:42
Exactly what I did to get around it :)
```
  "message_format": "({{{[kubernetes.pod_name]}}}) {{message}}"
```

and I also changed `app.js` 
```
  $scope.onClick = function (name,value) {
    $scope.userSearchText = name.replace(/\[|\]/g,'') + ': "' + value + '"';
    $scope.onSearchClick();
  };
```
to handle the `onClick` correctly.

**Comment by sivasamyk** [comment] 2017-06-11 15:45
When nested_objects is true, logtrail flattens the source object. This is not working well with handlebar templates. Will fix in next release.

**Comment by sasso** [comment] 2017-06-11 15:45
Also for some reason, if you have your key for the message set to `log` handlebars will not render it... I banged my head to figure out why that is but in the end, I did I quick fix by mapping `message` to `source['message']`...

```
    if (message_format) {
      source['message'] = message
      event['message'] = template(source);
    } else {
      event['message'] = escape(message);
    }
```

**Comment by sivasamyk** [comment] 2017-06-11 15:54
Also for some reason, if you have your key for the message set to log - You mean when the "message" under fields is mapped to log? Can you show me the logtrail.json in this case with a sample ES document?

**Comment by sasso** [comment] 2017-06-11 16:02
```
{
  "index_patterns" : [
    {      
      "es": {
        "default_index": "kubernetes-*",
        "allow_url_parameter": false       
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : true,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
          "timestamp" : "@timestamp",
          "display_timestamp" : "@timestamp",
          "hostname" : "kubernetes.namespace_name",
          "program": "kubernetes.container_name",
          "message": "log"
        },
        "message_format": "({{{[kubernetes.pod_name]}}}) {{message}}"
      }
    }  
  ]
}
```

```
{
  "_index": "kubernetes-2017-06-11",
  "_type": "kinesis",
  "_id": "49574043857871348013011112870811937926104321015536419026.0",
  "_score": null,
  "_source": {
    "log": "2017/06/11 16:00:00 agent.go:161: Enqueue event plugins.GitSync:update for git_sync\n",
    "stream": "stderr",
    "time": "2017-06-11T16:00:00.372718463Z",
    "app": {},
    "docker": {
      "container_id": "63831b6ada86ae5385e2ae288031380bd990c747b1d5ce055ec1963bed287915"
    },
    "kubernetes": {
      "container_name": "api",
      "namespace_name": "production-codeflow",
      "pod_name": "codeflow-api-48836766-6phdx"
    },
    "@timestamp": "2017-06-11T16:00:00.372+0000",
    "fluent_converted_timestamp": "2017-06-11T16:00:00.372+0000"
  },
  "fields": {
    "@timestamp": [
      1497196800372
    ],
    "time": [
      1497196800372
    ],
    "fluent_converted_timestamp": [
      1497196800372
    ]
  },
  "highlight": {
    "kubernetes.pod_name": [
      "codeflow-@kibana-highlighted-field@codeflow@/kibana-highlighted-field@-api-48836766-6phdx"
    ],
    "kubernetes.namespace_name": [
      "production-@kibana-highlighted-field@codeflow@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1497196800372
  ]
}
```

**Comment by sivasamyk** [comment] 2017-06-11 16:06
Setting message_format to `"message_format": "({{{[kubernetes.pod_name]}}}) {{{log}}"` is not working?

**Comment by sasso** [comment] 2017-06-11 16:09
for some reason, it's not rendering it ¯\_(ツ)_/¯. I tried setting other fields and it worked... maybe there is a length issue or it's overwritten in handlebars, or maybe I was just too fucked up and did something wrong :)

**Comment by sivasamyk** [comment] 2017-06-11 16:12
Hmm. Thats strange. Let me see if I can reproduce this issue with similar message format.

**Comment by sivasamyk** [comment] 2017-06-11 16:15
I just realized in the above example I missed a bracket : `"({{{[kubernetes.pod_name]}}}) {{{log}}}"`.  I assume this you have given proper braces in your installation.

**Comment by sasso** [comment] 2017-06-11 16:16
also here is the link to the repo where I did all the changes `https://github.com/checkr/kibana`

We use `5.3.2` AWS ES so I had to fork and update `package.json` to have the latest and the greatest fixes from 5.4.x

**Comment by jchannon** [comment] 2017-06-15 12:36
I see this has been merged, any ETA on a new release? Thanks

**Comment by sivasamyk** [comment] 2017-06-16 01:39
Will do a release on coming weekend.

**Comment by sivasamyk** [comment] 2017-06-16 14:32
Issue fixed in latest release. Download the release from https://github.com/sivasamyk/logtrail/releases/download/v0.1.15/logtrail-5.4.1-0.1.15.zip

**Comment by jchannon** [comment] 2017-06-16 14:57
I get errors : 

```
{
  "index_patterns" : [
    {
      "es": {
        "default_index": "fluentd-*",
        "allow_url_parameter": false
      },
      "tail_interval_in_seconds": 10,
      "es_index_time_offset_in_seconds": 0,
      "display_timezone": "local",
      "display_timestamp_format": "MMM DD HH:mm:ss",
      "max_buckets": 500,
      "nested_objects" : true,
      "default_time_range_in_days" : 0,
      "max_hosts": 100,
      "max_events_to_keep_in_viewer": 5000,
      "fields" : {
        "mapping" : {
            "timestamp" : "@t",
            "display_timestamp" : "@t",
            "hostname" : "@log_name",
            "program": "info.Component",
            "message": "info.Message"
        },
        "message_format": "{{{info.RequestId}}} {{{info.Component}}} {{{info.Method}}} {{{info.Message}}}"
      }
    }
  ]
}
```

```
elasticsearch_1  | [2017-06-16T14:53:03,564][WARN ][o.e.d.r.a.RestFieldStatsAction] [_field_stats] endpoint is deprecated! Use [_field_caps] instead or run a min/max aggregations on the desired fields.
kibana_1         | Error while validating ES TypeError: Cannot read property 'min_value' of undefined
kibana_1         |     at /usr/share/kibana/plugins/logtrail/server/routes/validate_es.js:30:18
kibana_1         |     at bound (domain.js:280:14)
kibana_1         |     at runBound (domain.js:293:12)
kibana_1         |     at tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)
kibana_1         |     at Promise._settlePromiseFromHandler (/usr/share/kibana/node_modules/bluebird/js/main/promise.js:503:31)
kibana_1         |     at Promise._settlePromiseAt (/usr/share/kibana/node_modules/bluebird/js/main/promise.js:577:18)
kibana_1         |     at Promise._settlePromises (/usr/share/kibana/node_modules/bluebird/js/main/promise.js:693:14)
kibana_1         |     at Async._drainQueue (/usr/share/kibana/node_modules/bluebird/js/main/async.js:123:16)
kibana_1         |     at Async._drainQueues (/usr/share/kibana/node_modules/bluebird/js/main/async.js:133:10)
kibana_1         |     at Immediate.Async.drainQueues (/usr/share/kibana/node_modules/bluebird/js/main/async.js:15:14)
kibana_1         |     at runCallback (timers.js:666:20)
kibana_1         |     at tryOnImmediate (timers.js:639:5)
kibana_1         |     at processImmediate [as _immediateCallback] (timers.js:611:5)
```

And in logtrail UI I see:
![screen shot 2017-06-16 at 15 44 20](https://user-images.githubusercontent.com/105126/27232005-724a6b2c-52ac-11e7-9114-c9aadf6dc7b6.png)

**Comment by sivasamyk** [comment] 2017-06-16 15:06
What is the elasticsearch version you are using? 5.4.1?

**Comment by jchannon** [comment] 2017-06-16 15:06
yup 5.4.1

**Comment by sivasamyk** [comment] 2017-06-16 15:22
Looks like _field_stats API used by logtrail is deprecated in 5.4.1. Will check in my local setup.

**Comment by sivasamyk** [comment] 2017-06-16 15:56
@jchannon what this working fine in earlier logtrail release? From your logtrail.json file I see that timestamp field is mapped to "@t" field in elasticsearch. Can you please check if this field exists?

**Comment by jchannon** [comment] 2017-06-16 16:14
Ah my bad, I changed it and forgot to alter it.  All working now!

**Comment by sivasamyk** [comment] 2017-06-16 16:15
great. Happy logging!

**Closed by sivasamyk** 2017-06-16 16:15 UTC
Labels: bug
